name: Bug Report
description: Please do not use bug reports for support issues
labels: [bug, needs-review]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Note: Please use Discussions for support issues.
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: List each action required in order to reproduce the issue.
      placeholder: |
        1. Go to [...]
        2. Tap on [...]
        3. Scroll down to [...]
        4. See error
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
  - type: input
    id: version-pifire-android
    attributes:
      label: PiFire Android Version
      description: What version of PiFire Android are you running?
      placeholder: ex. v1.3.2
    validations:
      required: true
  - type: input
    id: version-pifire
    attributes:
      label: PiFire Server Version
      description: What version of PiFire Server are you running?
      placeholder: ex. v1.2.2
    validations:
      required: true
  - type: input
    id: mobile-device
    attributes:
      label: Mobile Device
      description: What device are you using?
      placeholder: ex. Pixel 5, Samsung S21
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.